<? if($row['callnumber'] != 'Unknown'): ?>
    <? $check = (isset($row['check']) && $row['check']); ?>
    <? $checkStorageRetrievalRequest = (isset($row['checkStorageRetrievalRequest']) && $row['checkStorageRetrievalRequest']); ?>
    <? $checkILLRequest = (isset($row['checkILLRequest']) && $row['checkILLRequest']); ?>
    <? if (isset($row['barcode']) && $row['barcode'] != "" && !$this->driver->isEBook()): ?>
<dl class="dl-horizontal">
    <? if (isset($row['callnumber'])): ?>
    <dt><?=$this->transEsc('Call Number')?>:</dt>
    <dd><?=$row['callnumber']?></dd>
    <? endif; ?>
    
    <dt><?=$this->transEsc('live_status')?>:</dt>
    
    <? if (isset($row['use_unknown_message']) && $row['use_unknown_message']): ?>
        <dd class="text-muted"><?=$this->transEsc("status_unknown_message")?></dd>
    <? else: ?>
            <? if ($row['availability']): ?>
              <? /* Begin Available Items (Holds) */ ?>
               <dd class="text-success"><?=$this->transEsc("Available")?><link property="availability" href="http://schema.org/InStock" /></dd>
              <? if (isset($row['link']) && $row['link']): ?>
                <a class="hasicon <?=$check ? 'checkRequest ' : ''?>inlineblock <? if(!$this->client()->is('koha_link')): ?>modal-link modal-remote<? endif; ?>  external hasicon" data-name="aDIS BOSS2" data-size="md" href="<?=$this->recordLink()->getRequestUrl($row['link'])?>" title="<?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?>"></a>
              <? endif; ?>
              <? if (isset($row['storageRetrievalRequestLink']) && $row['storageRetrievalRequestLink']): ?>
                <a class="hasicon <?=$checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest ' : ''?> <? if(!$this->client()->is('koha_link')): ?>modal-link modal-remote<? endif; ?> external hasicon placeStorageRetrievalRequest" data-name="aDIS BOSS2" data-size="md" href="<?=$this->recordLink()->getRequestUrl($row['storageRetrievalRequestLink'])?>" title="<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?></a>
              <? endif; ?>
              <? if (isset($row['ILLRequestLink']) && $row['ILLRequestLink']): ?>
                <a class="hasicon <?=$checkILLRequest ? 'checkILLRequest ' : ''?>inlineblock <? if(!$this->client()->is('koha_link')): ?>modal-link modal-remote<? endif; ?> external hasicon placeILLRequest" data-name="aDIS BOSS2" data-size="md" href="<?=$this->recordLink()->getRequestUrl($row['ILLRequestLink'])?>"  title="<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?></a>
              <? endif; ?>
              <? if ($this->client()->is('always_place_hold')): ?>
                <a class="<?=$check ? 'checkRequest' : ''?> <? if(!$this->client()->is('koha_link')): ?>modal-link modal-remote<? endif; ?> external hasicon inlineblock " data-name="aDIS BOSS2" data-size="md" href="<?=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc($check ? "Check Recall" : "Recall This")?></a>
              <? endif; ?>              
            <? else: ?>
              <? /* Begin Unavailable Items (Recalls) */ ?>
              <dd class="text-danger"><?=$this->transEsc($row['status'])?>
              <? if (isset($row['returnDate']) && $row['returnDate']): ?>&ndash; <span class="small"><?=$this->escapeHtml($row['returnDate'])?></span><? endif; ?>
              <? if (isset($row['duedate']) && $row['duedate']): ?>
                &ndash; <span class="small"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($row['duedate'])?></span>
              <? endif; ?>
              </dd>
              <? if (isset($row['requests_placed']) && $row['requests_placed'] > 0): ?>
                <dd><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($row['requests_placed'])?></dd>
              <? endif; ?>
              <? if (isset($row['link']) && $row['link']): ?>
                <!-- Vormerken / Möglichkeit einer Vormerkung prüfen -->
                <dd>
                    <a class="<?=$check ? 'checkRequest' : ''?> <? if(!$this->client()->is('koha_link')): ?>modal-link modal-remote<? endif; ?> external hasicon inlineblock " data-name="aDIS BOSS2" data-size="md" href="<?=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc($check ? "Check Recall" : "Recall This")?></a>                   
                </dd>
              <? endif; ?>
            <? endif; ?>
          <? endif; ?>   

        <dd>
        </dd>
        <? if (isset($row['part']) && strlen($row['part']) > 0): ?>
            <dd><?=$this->escapeHtml($row['part'])?></dd>
        <? endif; ?>
        <? if (isset($row['about']) && count($row['about']) > 0): ?>
            <dd> <?=$this->escapeHtml(implode(', ', $row['about']))?></dd>        
        <? endif; ?>
      </dl>
<? endif; ?>
<? endif; ?>