<script> 
var $buoop = {
        vs:{i:10,f:35,o:27.1,s:5.1,c:30},
        reminder: 24,        
        test: false,
    };

function $buo_f(){ 
 var e = document.createElement("script"); 
 e.src = "/themes/bodensee/js/vendor/update.min.js"; 
 document.body.appendChild(e);
};
try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
catch(e){window.attachEvent("onload", $buo_f)}
</script> 
	