<? $truncate = 60?> 
<? $rand = rand(0, 1000)?>
<a class="dropdown-toggle btn library-toggle" id="libraryselector-<?=$rand?>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" title="<?=implode(', ', $this->client()->getIsils())?>">    
    <span class="caret"></span><?=$this->transEsc('Bibliothek')?>
</a>
    <ul class="dropdown-menu column-2" aria-labelledby="libraryselector-<?=$rand?>" role="menu">
        <li role="presentation" class="dropdown-header"><?=$this->escapeHTML('Baden-Württemberg')?></li>
        <? foreach ($this->libraries()->getByCountryId(\Bsz\Config\Libraries::ID_BAWUE) as $library): ?>
        <? $isil = $library->getIsil();
           $url = $this->url('saveisil',['isil' => $isil] )?>
        <li role="none presentation" <? if (in_array($isil, $this->client()->getIsils())): ?>class="active"<? endif;?>>
            <a role="menuitem" href="<?=$this->escapeHtmlAttr($url)?>"><?=$this->escapeHtml($this->truncate($library->getName(), $truncate))?></a>
        </li>
        <? endforeach; ?>
        <li role="none presentation" class="dropdown-header"><?=$this->escapeHTML('Saarland')?></li>
        <? foreach ($this->libraries()->getByCountryId(\Bsz\Config\Libraries::ID_SAARLAND) as $library): ?>
            <? $isil = $library->getIsil();
            $url = $this->url('saveisil',['isil' => $isil] )?>
            <li role="presentation" <? if (in_array($isil, $this->client()->getIsils())): ?>class="active"<? endif;?>>
                <a role="menuitem" href="<?=$this->escapeHtmlAttr($url)?>"><?=$this->escapeHtml($this->truncate($library->getName(), $truncate))?></a>
            </li>
        <? endforeach; ?>
        <li role="none presentation" class="dropdown-header"><?=$this->escapeHTML('Sachsen')?></li>
        <? foreach ($this->libraries()->getByCountryId(\Bsz\Config\Libraries::ID_SACHSEN) as $library): ?>
            <?  $isil = $library->getIsil();
                $url = $this->url('saveisil',['isil' => $isil] )?>
            <li role="presentation" <? if (in_array($isil, $this->client()->getIsils())): ?>class="active"<? endif;?>>
                <a role="menuitem" href="<?=$this->escapeHtmlAttr($url)?>"><?=$this->escapeHtml($this->truncate($library->getName(), $truncate))?></a>
            </li>
        <? endforeach; ?>
   
    </ul>

