<? $url = $this->recommend->getURL(); 
   $sourceTitle = $this->recommend->getSourceTitle(); 
   $imageName = $this->recommend->getImageName(); 
   $colNumber = $this->recommend->getColNumber();
   $label = $this->recommend->getLabel();
   
?>
<? if (!empty($url)): ?>
        <? if (!empty($label)): ?>
            <h4><?=$this->transEsc($label)?></h4>
        <? endif; ?>
        <div class="searchbutton col-12 col-md-<?=$colNumber?> col-xs-<?=$colNumber?>" style="padding-left:2px;padding-right:2px;">
                <a href="<?=$this->escapeHtmlAttr($url)?>" title="<?=$this->transEsc('Search')?> in <?=$this->escapeHtmlAttr($sourceTitle)?>" target="_blank">
                    <img class="img-responsive img-rounded" src="<?=$this->imageLink('/searchbuttons/'.$imageName )?>" alt="<?=$this->transEsc('Search')?> in <?=$sourceTitle ?>"  title="<?=$this->transEsc('Search')?> in <?=$sourceTitle ?>"/>
                </a>
        </div>
<? endif; ?>

