<? 
    $hiddenFilters = $this->searchMemory()->getLastHiddenFilters($this->searchClassId);
    $hiddenFilterString = '';
    foreach ($hiddenFilters as $key => $filter) {
        foreach ($filter as $value) {
            $hiddenFilterString .= '&hiddenFilters[]=' . $this->escapeHtmlAttr($key) . ':' . $this->escapeHtmlAttr($value);
        }
    }
?>
<div class="row" vocab="http://schema.org/" resource="#record">    
    <div class="col-xs-4 col-sm-3 col-xs-offset-4 col-sm-offset-0 pull-right-sm" >
<?
  $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'medium', '#');
  $cover = $coverDetails['html'];
  $thumbnail = false;
  $thumbnailAlignment = $this->record($this->driver)->getThumbnailAlignment('result');
  if ($cover): ?>
    <? if ($coverDetails['html'] !== ''): ?> 

            <?=$cover ?>
    <? endif; ?>
  <? else: ?>
    <div class="recordcover unavailable <?=$this->mapper()->mapIcon($this->driver->getFormats())?>">     
        <span class=""></span>
    </div>
<? endif; ?>   

<? /* Display qrcode if appropriate: */ ?>
        <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
        <? if($QRCode): ?>
          <span class="hidden-xs">
            <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
          </span>
        <? endif; ?>
      <?=$this->record($this->driver)->getPreviews()?>
    </div>
    <div class="col-xs-12 col-sm-9">
        <? 
           $title = $this->driver->getTitle();
           $subtitle = $this->driver->getTitleSection();
        ?>
        <h3 property="name">
        <?=$this->escapeHtml($title)?> <small><?=$this->string()->cleanEsc($subtitle)?></small>
        <?=$this->render('RecordDriver/SolrDefault/parts/dedup-tooltip.phtml', ['driver' => $this->driver])?>  
        </h3>

        <? if ($this->userlist()->getMode() !== 'disabled'): ?>
          <? /* Display the lists that this record is saved to */ ?>
          <div class="savedLists hidden alert alert-info" id="savedLists">
            <strong><?=$this->transEsc("Saved in")?>:</strong>
          </div>
        <? endif; ?>
        <?/* Display Main Details */?>
        <table class="table table-striped">        
            <? $container = $this->driver->getContainer(); if (count($container) > 0 ) : ?>
            <tr>
                <th><?=$this->transEsc('collective_editions')?>:</th>
                <td><? foreach($container as $cont): ?>
                    <a class="internal" href="<?=$this->RecordLink()->getUrl($cont)?>"><?=$this->string()->cleanEsc($cont->getTitle())?></a><br/>
                <? endforeach; ?></td>
            </tr>
            <? endif; ?>      

            <? $volume = $this->driver->getVolume(); ?>
            <? if (!empty($volume)): ?>
                <tr>
                  <th><?=$this->transEsc('Volume/Issue')?>: </th>
                  <td><?=$this->escapeHTML($volume)?></td>
                </tr>
            <? endif; ?> 

            <?=$this->render('RecordDriver/SolrDefault/parts/series.phtml')?>
            <? $journalTitle = $this->driver->getContainerTitle(); 
              $issue=$this->driver->getContainerIssue(); 
              $relParts=$this->driver->getContainerRelParts(); 
              $year=$this->driver->getContainerYear(); 
              $pages=$this->driver->getContainerPages(); 
            if ($this->driver->isArticle() && !empty($journalTitle)): ?>
                 <tr>
                <th><?=$this->transEsc('Published in')?>: </th>
                <td>
                       <?= $this->string()->cleanEsc($journalTitle)?><!--
                    --><? if (!empty($issue)): ?><?= $this->string()->cleanEsc($issue) ?><? endif; ?><!--
                    --><? if (!empty($relParts)): ?>. - <?=$relParts?><? else: ?><? if (!empty($year)): ?>. - <?=$this->string()->cleanEsc($year)?><? endif; ?><? if (!empty($pages)): ?>, S. <?=$pages?><? endif; ?><? endif; ?>            
                </td>
            </tr>
            <? endif; ?>
            
            <? $journalIssue = $this->driver->getContainerIssue(); 
               $journalYear= $this->driver->getContainerYear(); 
               if (!empty($journalIssue) && !empty($journalYear)): ?>
            <tr>
                <th><?=$this->transEsc('Issue')?>:</th>
                <td>
                  <?=$this->string()->cleanEsc($journalIssue)?>
                  <? if (!empty($journalYear)) : ?>
                      / <?=$this->string()->cleanEsc($journalYear)?>
                  <? endif ; ?>
                </td>
            </tr>
            <? endif; ?>     
            
            <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
            <? if (!empty($nextTitles)): ?>
            <tr>
                <th><?=$this->transEsc('New Title')?>: </th>
                <td><? foreach($nextTitles as $field): ?>
                    <a href="<?=$this->url('search-results')?>?lookfor=%22<?=urlencode($field)?>%22&amp;type=AllFields&amp;filter[]=~material_content_type:%22Journal/Magazine%22<?= $hiddenFilterString ?>"><?=$this->escapeHtml($field)?></a><br/>          
                  <? endforeach; ?></td>
            </tr>
            <? endif; ?>
            
            <? if (!empty($prevTitles)): ?>
            <tr>
                <th><?=$this->transEsc('Previous Title')?>: </th>
                <td>
                  <? foreach($prevTitles as $field): ?>
                     <a href="<?=$this->url('search-results')?>?lookfor=%22<?=urlencode($field)?>%22&amp;type=AllFields&amp;filter[]=~material_content_type:%22Journal/Magazine%22<?= $hiddenFilterString ?>"><?=$this->escapeHtml($field)?></a><br/>          
                  <? endforeach; ?>
                </td>
            </tr>
            <? endif; ?>
            
            <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
            <? $noLivePrimaryAuthor = $this->driver->getPrimaryAuthorNoLive(); ?>
            <? $gnd_author = preg_replace('/\(.*\)/', '', $this->driver->getPrimaryAuthorGND()); ?>
            <? if (isset($authors['main']) && !empty($authors['main'])): ?>
            <tr>
                <th><?=$this->transEsc('Main Author')?>: </th>
                <td property="author">
                    <a class="author" href="<?=$this->url('search-results')?>?lookfor=<?=urlencode($noLivePrimaryAuthor)?>&amp;type=Author<?= $hiddenFilterString ?>"><?=$this->escapeHtml($authors['main'])?></a>
                    <? if ($gnd_author != ''): ?>
                       (<a data-placement="right" data-toggle="tooltip" title="<?=$gnd_author?>" class="searchLink" href="<?=$this->url('search-results')?>?lookfor=gnd_from:<?= $gnd_author ?>&amp;type=AllFields<?= $hiddenFilterString ?>">GND-ID</a>)
                    <? endif; ?>
                </td>
            </tr>
            <? endif; ?>
            
            <? if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
            <tr>
                <th><?=$this->transEsc('Corporate Author')?>: </th>
                <td property="creator">
                <? foreach ($authors['corporate'] as $corp): ?>
                    <a class="author" href="<?=$this->url('search-results')?>?lookfor=<?=urlencode($corp)?>&amp;type=Author<?= $hiddenFilterString ?>"><?=$this->escapeHtml($corp)?></a><br/>
                <? endforeach; ?>
                </td>
            </tr>
            <? endif; ?>
            
            <? if (isset($authors['secondary']) && !empty($authors['secondary'])): ?>
            <? $noLiveSecondaryAuthors = $this->driver->getSecondaryAuthorsNoLive(); ?>
            <? $gnd_au2 = preg_replace('/\(.*\)/', '', $this->driver->getSecondaryAuthorGND()); ?>
            <? $role_au2 = $this->driver->getSecondaryAuthorsRole(); ?>
            <tr>
                <th><?=$this->transEsc('Other Authors')?>: </th>
                <td><? $i = 0;?>
                    <span>
                    <? foreach ($authors['secondary'] as $k => $field): ?>
                        <?=($i++ == 0)?'':', '?>
                        <span property="contributor">
                            <a class="author" href="<?=$this->url('search-results')?>?lookfor=<?=urlencode($noLiveSecondaryAuthors[$k])?>&amp;type=Author<?= $hiddenFilterString ?>">
                                <?=$this->escapeHtml($field)?>
                            </a>
                        </span>
                        <? if (isset($gnd_au2[$k])): ?>
                            (<a data-placement="right" data-toggle="tooltip" title="<?=$gnd_au2[$k]?>" class="hidden-print searchLink" href="<?=$this->url('search-results')?>?lookfor=gnd_from:<?= $gnd_au2[$k] ?>&amp;type=AllFields<?= $hiddenFilterString ?>">GND-ID</a><span class="visible-print">GND-ID: <?=$gnd_au2[$k]?></span>)<? endif; ?><? if (isset($role_au2[$k])): ?>; <?=$this->transEsc('CreatorRoles::'.$role_au2[$k]);?><? endif; ?>
                    <? endforeach; ?>
                    </span>
                </td>
            </tr>
            <? endif; ?>

            <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
            <tr>
                <th><?=$this->transEsc('Format')?>: </th>
                <td><? foreach($this->mapper()->simplify($this->driver->getFormats()) as $format): ?>
                    <span><?=$this->transEsc($format)?></span>
                    <? endforeach; ?></td>
            </tr>
            <? endif; ?>  

            <? $scale = $this->driver->getScale(); if (!empty($scale)): ?>
            <tr>
                <th><?=$this->transEsc('Scale')?>: </th>
                <td>
                    <?=$this->escapeHtml($scale)?><br/>
                </td>
            </tr>
            <? endif; ?>    
            
            <? $physical = $this->driver->getPhysicalDescriptions(); if (!empty($physical)): ?>
            <? $contentDisplayed = true; ?>
            <tr>
                <th><?=$this->transEsc('Physical Description')?>: </th>
                <td><? foreach ($physical as $field): ?>
                    <?=$this->escapeHtml($field)?><br/>
                  <? endforeach; ?></td>
            </tr>
            <? endif; ?>           

            <?  
               $isbn = $this->driver->getCleanISBN(); 
               $issn = $this->driver->getCleanISSN();
               if (!empty($isbn)): ?>
            <tr>
                <th><?=$this->transEsc('ISBN')?>:</th>
                <td><?=$this->driver->getCleanISBN()?></td>
            </tr>
            <? elseif (!empty($issn)): ?>
            <tr>
                <th><?=$this->transEsc('ISSN')?>:</th>
                <td><?=$this->driver->getCleanISSN()?></td>
            </tr>
            <? endif; ?>

            <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
            <tr>
                <th><?=$this->transEsc('Language')?>: </th>
                <? $count = 0 ?>
                <td><? foreach ($langs as $lang): ?><? if($count > 0):?>; <?endif;?><?= $this->transEsc($lang)?><? $count++?><? endforeach; ?>
                </td>
            </tr>
            <? endif; ?> 
            
            <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
            <tr>
                <th><?=$this->transEsc('Published')?>: </th>
                <td>
                  <? foreach ($publications as $field): ?>
                    <span property="publisher" typeof="Organization">
                    <? $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
                      <span property="location"><?=$this->escapeHtml($pubPlace)?></span> : 
                    <? endif; ?>
                    <? $pubName = $field->getName(); if (!empty($pubName)): ?>
                      <span property="name"><?=$this->escapeHtml($pubName)?></span>
                    <? endif; ?>
                    </span>
                    <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
                      <span property="publicationDate"><?=$this->escapeHtml($pubDate)?></span>
                    <? endif; ?>
                    <br/>
                  <? endforeach; ?>
                </td>
            </tr>
            <? endif; ?>
            
            <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
            <tr>
                <th><?=$this->transEsc('Edition')?>: </th>
                <td property="bookEdition"><?=$this->escapeHtml($edition)?></td>
            </tr>
            <? endif; ?>
            
            <? $childRecordCount = $this->driver->tryMethod('getChildRecordCount'); if ($childRecordCount): ?>
            <tr>
                <th><?=$this->transEsc('child_records')?>: </th>
                <td><a href="<?=$this->recordLink()->getChildRecordSearchUrl($this->driver)?>"><?=$this->transEsc('child_record_count', array('%%count%%' => $childRecordCount))?></a></td>
            </tr>
            <? endif; ?>    
            <?=$this->render('RecordDriver/SolrDefault/parts/subjects.phtml')?>

            <?
                  $openUrl = $this->openUrl($this->driver, 'record');
                  $openUrlActive = $openUrl->isActive();
                  // Account for replace_other_urls setting
                  $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
            ?>

            <? // Show local urls or SWB-links but not both ?>
            <? $localUrls = $this->driver->getLocalUrls()?>     
            <? if (!empty($localUrls[0]['url'])): ?>
                <tr>
                    <th><?=$this->transEsc('Local Online Access')?>: </th>
                    <td>
                        <? foreach ($localUrls as $current):  ?>
                            <? $pos = strpos($current['label'], ' | '); ?>
                            <? $len = strlen($current['label']); ?>
                            <? if ($this->client()->is('local_url_help_regex')): ?>
                                <a class="external localUrls" href="<?=str_replace('http://dx.doi.org', 'https://doi.org', $current['url'])?>"><?=$pos ? $this->transEsc(substr($current['label'], 0, $pos)) : $this->transEsc($current['label'])?></a>  <?=$pos ? preg_replace($this->client()->getHelpRegEx(), "<a class='external' href='".$this->client()->getHelpUrl()."'>".$this->client()->getHelpGroups()."</a>",  $this->transEsc(substr($current['label'], $pos+3, $len)) ): ''?><br/>
                            <? else: ?>                        
                                <a class="external localUrls" href="<?=str_replace('http://dx.doi.org', 'https://doi.org', $current['url'])?>"><?=$pos ? $this->transEsc(substr($current['label'], 0, $pos)) : $this->transEsc($current['label'])?></a> <?=$pos ? $this->transEsc(substr($current['label'], $pos+3, $len)) : ''?><br/>
                            <? endif; ?>                    
                        <? endforeach; ?>
                    </td>
                </tr>        
            <? else: ?>
                <? if (!empty($urls)): ?>
                    <tr>
                      <th><?=$this->transEsc('External Resources')?>: </th>
                      <td><? foreach ($urls as $current): ?>
                              <a class="external" href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->transEsc($current['desc'])?></a><br/>
                          <? endforeach; ?></td>
                    </tr>
                <? endif; ?>
            <? endif; ?>
      <? $html = $openUrl->renderTemplate() ?>
      <? if ($openUrlActive && strlen($html) > 0): ?>
      <tr>
          <th><?=$this->transEsc('Link Resolver')?>:</th>
          <td><?=$html?></td>                
      </tr>
      <? endif; ?>
      
      <? if( strlen($this->driver->getConsortium()) > 0): ?>
        <tr>
            <th><?=$this->transEsc('Network')?>:</th>
            <td><?=$this->driver->getConsortium() ?></td> 
        </tr>          
      <? endif; ?> 

      
      <? if ($this->usertags()->getMode() !== 'disabled'): ?>
        <? $tagList = $this->driver->getTags(); ?>
        <tr>
            <th><?=$this->transEsc('Tags')?>: </th>
            <td>
                <span class="pull-right">
                  <i class="fa fa-plus"></i> <a id="tagRecord" class="modal-link" href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" title="<?=$this->transEsc('Add Tag')?>"><?=$this->transEsc('Add Tag')?></a>
                </span>
                <div id="tagList">
                  <? if (count($tagList) > 0): ?>
                    <? $i = 0; foreach ($tagList as $tag): ?><?=($i++ == 0)?'':', '?><a href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a> (<?=$this->escapeHtml($tag->cnt)?>)<? endforeach; ?>
                  <? else: ?>
                    <?=$this->transEsc('No Tags')?>, <?=$this->transEsc('Be the first to tag this record')?>!
                  <? endif; ?>
                </div>
            </td>
        </tr>        
        <? endif; ?>
              <? if ($this->searchTabs()->isILL($this->searchClassId)): ?>
        <?=$this->render('RecordDriver/SolrDefault/parts/illbutton.phtml')?>
      <? endif; ?>
    </table>
    <?/* End Main Details */?>
    </div>
</div>