<?
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = $this->render('search/searchbox.phtml');

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }
  
  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = false;

  
  $library = $this->libraries()->getFirstActive($this->client()->getIsils());
  
?>
<div class="col-sm-12 searchHomeContent">
<?php
  $ilsStatusScript = <<<JS
$(document).ready(function() {
  $.ajax({
      dataType: 'json',
      method: 'GET',
      data: {'offlineModeMsg':'ils_offline_home_message'},
      url: VuFind.path + '/AJAX/JSON?method=getIlsStatus',
      success: function(response) {
          $('.searchHomeContent').prepend(response.data);
      }
  });
});
JS;
  ?>
  <? if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
    <div class="alert alert-warning">
      <h2><?=$this->transEsc('ils_offline_title')?></h2>
      <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
      <p><?=$this->transEsc('ils_offline_home_message')?></p>
      <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
      <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
    </div>
  <? endif; ?>
  <div class="row">
      <? if ($this->client()->isIsilSession()): ?>      
          <div class="col-xs-5 col-sm-4 col-md-3">
              <img class="img-responsive" src="<?=$this->imageLink('logo/default.png')?>" alt="BSZ Logo" />
          </div>
      <? else: ?>
          <div class="col-md-9 col-xs-6  hidden-sm hidden-xs">
              <? if ($this->imageLink($this->clientAsset()->getHeader())): ?>
              <img src="<?=$this->imageLink($this->clientAsset()->getHeader()) ?>" class="img-responsive" alt="Aufmacherbild" />
              <? endif; ?>
          </div>
      <? endif; ?>
      <div class="col-xs-5 col-sm-3 pull-right">
          <?=$this->clientAsset()->getLogoHtml()?>
      </div>      
  </div>
  <div class="row form-group">   
      <div class="col-sm-12">          
          <? if(($this->client()->isIsilSession() && empty($this->client()->getIsils())) || !$this->client()->isIsilSession()): ?>          
            <h2><?=$this->transEsc('homepage_heading')?> <small><?=$this->transEsc('homepage_subheading')?></small></h2>         
          <? elseif($this->client()->isIsilSession() && $this->client()->hasIsilSession()): ?>
            <h2><?=$this->escapeHTML((string)$library)?> <small><?=$this->transEsc('homepage_subheading')?></small></h2>          
          <? endif; ?>
          
          <? if (strpos($this->translate('homepage_text'), '<') !== FALSE): ?>
            <p><?=$this->translate('homepage_text')?></p>
          <? else: ?>
            <p><?=$this->transEsc('homepage_text')?></p>
          <? endif; ?>
            
          
          
          <? if($this->client()->isIsilSession() && !$this->client()->hasIsilSession()): ?>
          <p><?=$this->translate('ill_select_library')?></p>
          <? endif; ?>
          <? if ($this->client()->isIsilSession()): ?>
              <?=$this->partial('bsz/illdropdown.phtml')?>
          <? endif; ?>
          <? // Set Maintenance hints with SetEnv MAINTENANCE_MODE "..." in httpd-vufind.conf ?>
        </div>
  </div>
  <div class="row">
      <div class="col-sm-12">
          <?=$this->flashmessages()?>         
          <? if ($this->client()->is('wlb_special_home')): ?>
                    <?= $this->render('bsz/wlb/'.$this->layout()->userLang.'.phtml')?>
          <? endif; ?>          
      </div>
  </div>
  
    <? if ($this->client()->getRSSFeed() !== null): ?>
        <div id="RSSFeedResultsDeferred" class="col-sm-6">
            <p><?=$this->transEsc("Loading")?>... <img src="<?=$this->imageLink('ajax_loading.gif')?>" /></p>
            <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, "var url = VuFind.path + '/AJAX/News?mod=StartpageNews';$('#RSSFeedResultsDeferred').load(url);", 'SET')?>        </div>    
    <? endif; ?>
    
    
  <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $ilsStatusScript, 'SET'); ?>
  
  <?//$this->context($this)->renderInContext("search/searchbox.phtml", ['ignoreHiddenFilterMemory' => true])?>
  <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, '$("#searchForm_lookfor").focus();', 'SET'); ?>
</div>

<? if (isset($facetList) && is_array($facetList)): ?>
  <div class="search-home-facets">
    <? foreach ($facetList as $field => $details): ?>
      <? if (isset($this->hierarchicalFacets) && in_array($field, $this->hierarchicalFacets)): ?>
        <? $this->headScript()->appendFile('vendor/jsTree/jstree.min.js'); ?>
        <? $this->headScript()->appendFile('facets.js'); ?>
        <? $sort = isset($this->hierarchicalFacetSortOptions[$field]) ? $this->hierarchicalFacetSortOptions[$field] : ''; ?>
        <?
        $script = <<<JS
$(document).ready(function() {
  initFacetTree($('#facet_{$this->escapeHtml($field)}'), false);
});
JS;
        ?>
        <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
        <div class="home-facet <?=$this->escapeHtmlAttr($field) ?>">
          <h2><?=$this->transEsc('home_browse') . ' ' . $this->transEsc($details['label'])?></h2>
          <div id="facet_<?=$this->escapeHtml($field)?>" class="jstree-facet"
              data-facet="<?=$this->escapeHtml($field)?>"
              data-path="<?=$this->url($basicSearch)?>"
              data-exclude="0"
              data-operator="AND"
              data-exclude-title="<?=$this->transEsc('exclude_facet')?>"
              data-sort="all">
          </div>
        </div>
        <noscript>
      <? endif; ?>
      <? $sortedList = $this->sortFacetList($this->results, $field, $details['list'], $basicSearch); ?>
      <div class="home-facet <?=$this->escapeHtmlAttr($field) ?>">
        <h2><?=$this->transEsc('home_browse') . ' ' . $this->transEsc($details['label'])?></h2>
        <div class="home-facet-container">
          <ul class="home-facet-list">
          <? /* Special case: two columns for LC call numbers... */ ?>
          <? if ($field == "callnumber-first"): ?>
            <? $i = 0; foreach ($sortedList as $url => $value): ?>
              <? if (!empty($value)): ?>
                <li><a href="<?=$url?>"><?=$this->escapeHtml($value)?></a></li>
              <? else: $i--; ?>
              <? endif; ?>
              <? if (++$i == 10): ?>
                  </ul><ul class="home-facet-list">
              <? endif; ?>
            <? endforeach; ?>
          <? /* Special case: collections */ ?>
          <? elseif ($field == 'hierarchy_top_title'): ?>
            <? $i = 0; foreach ($sortedList as $url => $value): ?>
              <? if (++$i > 10): ?>
                <li><a href="<?=$this->url('collections-home')?>"><strong><?=$this->transEsc("More options")?>...</strong></a></li>
                <? break; ?>
                <? endif; ?>
                <li><a href="<?=$this->url('collections-bytitle')?>?title=<?=urlencode($value)?>"><?=$this->escapeHtml($value)?></a></li>
            <? endforeach; ?>
          <? else: ?>
            <? $i = 0; foreach ($sortedList as $url => $value): ?>
              <? if (++$i > 10): ?>
                <li><a href="<?=$this->url($advSearch)?>"><strong><?=$this->transEsc("More options")?>...</strong></a></li>
                <? break; ?>
              <? elseif (!empty($value)): ?>
                <li><a href="<?=$url?>"><?=$this->escapeHtml($value)?></a></li>
              <? else: $i--; ?>
              <? endif; ?>
            <? endforeach; ?>
          <? endif; ?>
          </ul>
        </div>
      </div>
      <? if (isset($this->hierarchicalFacets) && in_array($field, $this->hierarchicalFacets)): ?>
        </noscript>
      <? endif; ?>
    <? endforeach; ?>
  </div>
<? endif; ?>
