<? if (count($searchTabs) > 0): ?>
  <ul class="nav nav-tabs" role="menu">
    <? foreach ($searchTabs as $tab): ?>
        <? if ($this->permission()->allowDisplay($tab['permission'])): ?>
          <li<?=$tab['selected'] ? ' class="active"' : ''?> role="none presentation">
            <a <?=$tab['selected'] ? '' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>>
                <i class="fa <?=$this->escapeHTMLAttr($tab['icon'])?>"></i>
                <span class="text"><?=$this->transEsc($tab['label']); ?></span></a>
          </li>
        <? elseif ($block = $this->permission()->getAlternateContent($tab['permission'])): ?>
            <?=$block?>
        <? endif; ?>
    <? endforeach; ?>
  </ul>
<? endif; ?>
