<? $account = $this->auth()->getManager(); ?>
<? if ($this->layout()->searchbox !== false && !$this->client()->is('disable_searchbar')): ?>
    <div class="navbar-left">
        <? if (!isset($frame)): ?>
            <button type="button" class="navbar-toggle btn btn-primary" data-toggle="collapse" data-target="#header-collapse">
                <span class="sr-only">Toggle navigation</span>
                <i class="fa fa-bars"></i>
            </button>    
        <? endif; ?>
        <?=$this->layout()->searchbox ?>    
    </div>
<? endif; ?>
  <? if (!isset($this->layout()->renderingError)): ?>
    <div class="collapse navbar-collapse" id="header-collapse">
      <nav>
        <ul class="nav navbar-nav navbar-right flip">
          <? if ($this->client()->isIsilSession()): ?>
            <li class="dropdown">
                <?=$this->partial('bsz/illdropdown.phtml')?>           
            </li>
          <? endif; ?>
          <? if ($this->feedback()->tabEnabled()): ?>
            <li>
              <a id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope" aria-hidden="true"></i> <?=$this->transEsc("Feedback")?></a>
            </li>
          <? endif; ?>
          <? $cart = $this->cart(); if ($cart->isActive()): ?>
            <li id="cartSummary">
              <a id="cartItems" data-lightbox title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
                <i class="fa fa-suitcase" aria-hidden="true"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?>
                <span class="full<?=!$cart->isFull() ? ' hidden' : '' ?>">(<?=$this->transEsc('bookbag_full') ?>)</span>
              </a>
            </li>
          <? endif; ?>
          <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
            <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
              <a href="<?=$this->url('myresearch-home', [], ['query' => ['redirect' => 0]])?>"><i class="fa fa-star" aria-hidden="true"></i> <?=$this->transEsc("Your Account")?></a>
            </li>
            <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
              <a href="<?=$this->url('myresearch-logout')?>" class="logout"><i class="fa fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?></a>
            </li>
            <li id="loginOptions"<? if($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
              <? if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                <a data-toggle="tooltip" data-placement="bottom" title="<?=$this->transEsc('Institutional Login Tooltip')?>" href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Institutional Login")?></a>
              <? else: ?>
                <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Login")?></a>
              <? endif; ?>
            </li>
          <? endif; ?>
          <? if(strlen($this->client()->getWebsite('adis')) > 0): ?>
            <li>
                <a class="external" href="<?=$this->client()->getWebsite('adis')?>"><i class="fa fa-user"></i> <?=$this->transEsc('header_login_link')?></a>
            </li>
          <? endif; ?>
          <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
            <li class="theme dropdown">
              <form method="post" name="themeForm" id="themeForm">
                <input type="hidden" name="ui"/>
              </form>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <? foreach ($this->layout()->themeOptions as $current): ?>
                  <li<?=$current['selected'] ? ' class="active"' : ''?>><a href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
                <? endforeach; ?>
              </ul>
            </li>
          <? endif; ?>

          <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
            <li class="language dropdown">
              <form method="post" name="langForm" id="langForm">
                <input type="hidden" name="mylang"/>
              </form>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="<?=$this->imageLink('flags/'.$this->layout()->userLang.'.png')?>" alt="Language Flag" /> <i class="fa fa-caret-down"></i></a>
              <ul class="dropdown-menu">
                <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                    <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>>
                        <a class="" href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()">
                            <img src="<?=$this->imageLink('flags/'.$langCode.'.png')?>" alt="Flag <?=$this->displayLanguageOption($langName)?>" />
                            <?=$this->displayLanguageOption($langName)?>
                        </a>
                    </li>  
                <? endforeach; ?>
              </ul>
            </li>
          <? endif; ?>
          <li class="home">
              <a class="lang-<?=$this->layout()->userLang ?>" href="<?=$this->url('home')?>"><i class="fa fa-home"></i><span class="sr-only"><?=$this->transEsc('Home')?></span>
              </a>  
          </li>
        </ul>
      </nav>
    </div>
  <? endif; ?>

