<?
    // Set page title.
    $this->headTitle($this->translate('Volumes') . ': ' . $this->driver->getBreadcrumb());
 
    $content = $this->tab->getContent();        
        

?>
<? if(isset($content) && count($content) > 0): ?>
<? $rand = rand(0, 9999)?>
<table class="table table-striped table-condensed tablesorter">
    <thead>
        <tr>
            <th class="col-xs-8"><?=$this->transEsc('Title')?></th>        
            <th class="col-xs-1"><?=$this->transEsc('Year')?></th>
            <th class="col-xs-2"><?=$this->transEsc('Author')?></th>        
        </tr>        
    </thead>
    <tbody>        
        <? $count = 1; foreach ($content as $result): ?>
        <tr <? if ($count > 10): ?> class="showmore-<?=$rand?> collapse multi-collapse"<? endif; ?>>
            <td><a class="internal"  href="<?=$this->recordLink()->getUrl($result, $this->overrideRecordLink)?>"><?=$this->string()->cleanEsc($result->getTitle())?> <?=$this->string()->cleanEsc($result->getTitleSection())?></a></td>
            <td><?=implode(', ',$result->getPublicationDates())?></td>
            <td><?=$result->getPrimaryAuthor()?></td>
        </tr>
    <? $count++ ?>  
    <? endforeach; ?>
    </tbody>
    <? if ($count > 10): ?> 
        <tfoot>
            <tr><td>
                <button id="more-articleslist" onclick="return moreChildren('articleslist')" class="btn btn-info btn-xs" data-toggle="collapse" data-target=".showmore-<?=$rand?>" aria-expanded="false">
                    <?=$this->transEsc('Showmore')?>
                </button>    
                <button onclick="return lessChildren('articleslist')" class="btn btn-info btn-xs hidden articleslist" data-toggle="collapse" data-target=".showmore-<?=$rand?>" aria-expanded="false">
                    <?=$this->transEsc('Showless')?>
                </button>     
            </td></tr>
        </tfoot>
    <? endif; ?>
</table>
<script type="text/javascript">
    $(document).ready(function() {
       $('.tablesorter').tablesorter({
            sortList : [[1,1]]
       }); 
    });
</script>
<? else: ?>
<p><?=$this->transEsc('nohit_heading')?></p>
<? endif; ?>
