<?
    // Set page title.
    $this->headTitle($this->translate('Libraries') . ': ' . $this->driver->getBreadcrumb());
    $content = $this->tab->getContent();        
?>

<? if(isset($content) && count($content) > 0): ?>
    
<table class="table table-striped table-condensed tablesorter">
    <thead>
        <tr>
            <th class="col-sm-1 col-xs-1 hidden-sm"><?=$this->transEsc('ISIL')?></th>
            <th><?=$this->transEsc('Library')?></th>        
            <th><?=$this->transEsc('Signatur')?></th>
            <th class="col-sm-2 col-xs-2"><?=$this->transEsc('Interlibrary Loan')?></th>
            <? if ($this->driver->isJournal()): ?><th><?=$this->transEsc('Collection')?></th><? endif; ?>

        </tr>        
    </thead>
    <tbody>
        <? foreach ($content as $result): ?>
        <tr>
            <td>
                <? if (isset($result['b']) && trim($result['b']) != ''): ?>
                    <span class="text-nowrap">
                    <a href=" https://sigel.staatsbibliothek-berlin.de/nc/suche/?isil=<?=trim($result['b'])?>" class="external">
                        <?=$this->escapeHtml($result['b'])?>
                    </a>
                    </span>
                <? else: ?>
                    <?=isset($result['b']) ? $this->escapeHtml($result['b']) : ''?>
                <? endif; ?>
            </td>
            <td>
                <? if (isset($result['homepage']) && isset($result['name']) && trim($result['homepage']) != ''): ?>
                    <a href="<?=$result['homepage']?>" class="external">
                        <?=$this->escapeHtml($result['name'])?>
                    </a>
                <? else: ?>
                    <?=isset($result['name']) ? $this->escapeHtml($result['name']) : ''?>
                <? endif; ?>
            </td>
            <td><?=isset($result['g']) ? $this->escapeHtml($result['g']) : ''?></td>
            <td><?=isset($result['ill_status']) ? $this->transEsc($result['ill_status']) : '-' ?></td>
            <? if ($this->driver->isJournal()): ?><td><?=isset($result['z']) ? $this->escapeHtml($result['z']) : ''?></td><? endif; ?>
        </tr>
        <? endforeach; ?>        
    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function() {
       $('.tablesorter').tablesorter({
           sortList : [[0,0]]
       }); 
    });
</script>
<? else: ?>
<p><?=$this->transEsc('nohit_heading')?></p>
<? endif; ?>
