<? if( $this->searchTabs()->isILL() && strlen($this->driver->getConsortium()) > 0): ?>
        <div class="ill-source">                
            <strong><?=$this->transEsc('Network')?>:</strong>
            <span><?=$this->driver->getConsortium() ?></span> 
        </div>          
<? endif; ?>
<? if (!$this->driver->isSubRecord()): ?>
    <div class="callnumAndLocation ajax-availability hidden">
    <? if ($this->driver->supportsAjaxStatus()): ?>
        <strong class="hideIfDetailed"><?=$this->transEsc('Call Number')?>:</strong>
        <span class="callnumber ajax-availability hidden">
            <?=$this->transEsc('Loading')?>...<br/>
        </span>
        <strong><?=$this->transEsc('Located')?>:</strong>
        <span class="location ajax-availability hidden">
            <?=$this->transEsc('Loading')?>...
        </span>
        <div class="locationDetails"></div>
    <? else: ?>
        <? $summCallNo = $this->driver->getCallNumber(); if (!empty($summCallNo)): ?>
            <strong><?=$this->transEsc('Call Number')?>:</strong> <?=$this->escapeHtml($summCallNo)?>
        <? endif; ?>
    <? endif; ?>
    </div>
<? endif; ?>
<? /* We need to find out if we're supposed to display an OpenURL link ($openUrlActive),
    but even if we don't plan to display the link, we still want to get the $openUrl
    value for use in generating a COinS (Z3988) tag -- see bottom of file.
*/

// Account for replace_other_urls setting
$openUrl = $this->openUrl($this->driver, 'results');
$openUrlActive = $openUrl->isActive();       
$urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
if (!is_array($urls)): 
    $urls = [];
endif;

$localUrls = $this->driver->getLocalUrls(); ?>            
<? // Show local Urls ?>
<? if (!empty($localUrls[0]['url'])): ?>
    <div>
        <? foreach ($localUrls as $current):  ?>
            <? $pos = strpos($current['label'], ' | '); ?>
            <? $len = strlen($current['label']); ?>
            <? if ($this->client()->is('local_url_help_regex')): ?>
                <a class="external" href="<?=str_replace('http://dx.doi.org', 'https://doi.org', $current['url'])?>"><?=$pos ? $this->transEsc(substr($current['label'], 0, $pos)) : $this->transEsc($current['label'])?></a>  <?=$pos ? preg_replace($this->client()->getHelpRegEx(), "<a class='external' href='".$this->client()->getHelpUrl()."'>".$this->client()->getHelpGroups()."</a>",  $this->transEsc(substr($current['label'], $pos+3, $len)) ): ''?><br/>
            <? else: ?>                        
                <a class="external" href="<?=str_replace('http://dx.doi.org', 'https://doi.org', $current['url'])?>"><?=$pos ? $this->transEsc(substr($current['label'], 0, $pos)) : $this->transEsc($current['label'])?></a> <?=$pos ? $this->transEsc(substr($current['label'], $pos+3, $len)) : ''?><br/>
            <? endif; ?>                    
        <? endforeach; ?>
    </div>
<? else: ?>
    <? // Show SWB-links ?>        
    <? if(!$this->driver->isCollection()): ?>
        <? if (count($urls) > 2): ?>
            <? $urls = array_slice($urls, 0, 3) ?>
        <? endif; ?>
        <? foreach ($urls as $current): ?>
            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" class="fulltext external"><?=($current['url'] == $current['desc']) ? $this->transEsc('Get full text') : $this->transEsc($current['desc'])?></a><br/>
        <? endforeach; ?>
    <? endif; ?>
<? endif; ?>      

<? // JOP resp. Redi Linkresolver  
   // see VuFind/View/Helper/Bodensee/OpenUrl.php 
   //     themes/bodensee/Helpers/openurl.phtml
   //     openurl.js
?>
<? if ($openUrlActive): ?>
    <?=$openUrl->renderTemplate() ?>
<? endif; ?>  
<?=$this->driver->supportsCoinsOpenUrl()?'<span class="Z3988" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenUrl()) . '"></span>':''?>
