 <?/* Display series section if at least one series exists. */?>
 <? 
    $hiddenFilters = $this->searchMemory()->getLastHiddenFilters($this->searchClassId);
    $hiddenFilterString = '';
    foreach ($hiddenFilters as $key => $filter) {
        foreach ($filter as $value) {
            $hiddenFilterString .= '&hiddenFilters[]=' . $this->escapeHtmlAttr($key) . ':' . $this->escapeHtmlAttr($value);
        }
    }
?>
<? $series = $this->driver->getSeries(); if (!empty($series)): ?>
<tr>
<th><?=$this->transEsc('Series')?>: </th>
<td>
  <? foreach ($series as $field): ?>
    <?/* Depending on the record driver, $field may either be an array with
       "name" and "number" keys or a flat string containing only the series
       name.  We should account for both cases to maximize compatibility. */?>
    <? if (is_array($field)): ?>
      <? if (!empty($field['name'])): ?>
        <a class="searchicon" href="<?=$this->record($this->driver)->getLink('series', $field['name'], $this->overrideRecordLink)?><?=$hiddenFilterString?>"><?=$this->escapeHtml($field['name'])?></a>
        <? if (!empty($field['number'])): ?>
          <?=$this->escapeHtml($field['number'])?>
        <? endif; ?>
        <br/>
      <? endif; ?>
    <? else: ?>
      <a class="searchicon" href="<?=$this->record($this->driver)->getLink('series', $field, $this->overrideRecordLink)?><?=$hiddenFilterString?>"><?=$this->escapeHtml($field)?></a><br/>
    <? endif; ?>
  <? endforeach; ?>
</td>
</tr>
<? endif; ?>