<?
  // Set page title.
  $this->headTitle($this->translate('Error'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  $this->layout()->breadcrumbs = '<li class="active">Error</li>';
?>

<div class="col-sm-12">
<h1><?=$this->transEsc('An error has occurred')?></h1>
<h2><?=$this->transEsc($this->message)?></h2>
<? if (isset($this->reason) && $this->reason): ?><b><?=$this->transEsc('Message')?>:</b> <?=$this->transEsc($this->reason)?><? endif; ?>    
</div>
