<div class="col-sm-12">    
    <h1><?=$this->transEsc('An error has occurred')?></h1>

    <? if ($this->showInstallLink): ?>
      <h3><a href="<?=$this->url('install-home')?>"><?=$this->transEsc('auto_configure_title', [], 'Auto Configure')?></a></h3>
      <?=$this->transEsc('auto_configure_description', [], 'If this is a new installation, you may be able to fix the error using VuFind\'s Auto Configure tool.')?>
      <h3><a href="<?=$this->url('upgrade-home')?>"><?=$this->transEsc('Upgrade VuFind')?></a></h3>
      <?=$this->transEsc('upgrade_description', [], 'If you are upgrading a previous VuFind version, you can load your old settings with this tool.')?>
    <? endif; ?>

    <? if (isset($this->display_exceptions)): ?>
      <h3>
        <b><?=$this->transEsc('ErrorMessage')?>:</b> <?=$this->escapeHtml($this->exception->getMessage())?>
      </h3>
    <? endif ?>

    <h4><?=$this->transEsc('Please try again later')?>...</h4>
</div>
