<table class="table table-condensed">
  <tr>
    <th><?=$this->transEsc('Location')?></th>
    <th><?=$this->transEsc('Call Number')?></th>
    <th><?=$this->transEsc('Status')?></th>
  </tr>
  <? $count = 0; foreach ($this->statusItems as $item): ?>
    <? if ($count++ == 5) break; // Show no more than 5 items ?>
        <? $class = 'text-success';
        $icon = 'fa-check';
        if ($item['availability'] == false) {
            $class = "text-danger";
            $icon = 'fa-times';
        }                    
                    
        $message = '';
        if (is_array($item['message']) && array_key_exists('en', $item['message'])) {
            $message = isset($item['message'][$this->layout()->userLang]) ? $item['message'][$this->layout()->userLang] : $item['message']['en'];
        }
    ?>
    <tr>
      <td class="fullLocation">
        <? $locationText = $this->transEsc('location_' . $item['location'], [], $item['location']); ?>
        <? if (isset($item['locationhref']) && $item['locationhref']): ?>
          <a href="<?=$item['locationhref']?>" target="_blank"><?=$locationText?></a>
        <? else: ?>
          <?=$locationText?>
        <? endif; ?>
      </td>
      <td class="fullCallnumber">
        <? if ($this->callnumberHandler): ?>
          <a href="<?=$this->url('alphabrowse-home') ?>?source=<?=$this->escapeHtmlAttr($this->callnumberHandler) ?>&amp;from=<?=$this->escapeHtmlAttr($item['callnumber']) ?>"><?=$this->escapeHtml($item['callnumber'])?></a>
        <? else: ?>
          <?=$this->escapeHtml($item['callnumber'])?>
        <? endif; ?>
      </td>
      <td class="fullAvailability">
        <? if (isset($item['use_unknown_message']) && $item['use_unknown_message']): ?>
         <span class="text-nowrap">
             <i class="fa <?=$this->escapeHtmlAttr($icon)?> <?=$class?>"></i>
             <?=$this->transEsc("status_unknown_message")?>
         </span>
        <? elseif ($item['availability']): ?>
          <span class="text-success text-nowrap">
            <i class="fa <?=$this->escapeHtmlAttr($icon)?> <?=$class?>"></i>
            <?=($item['reserve'] == 'Y') ? $this->transEsc("On Reserve") : $this->transEsc("Available")?>
          </span>
        <? elseif ($item['status'] === "On loan"): ?>
            <span class="text-danger text-nowrap">
                <i class="fa <?=$this->escapeHtmlAttr($icon)?> <?=$class?>"></i>
                <?=$this->transEsc("On loan")?>
            </span>
            <? if (isset($item['duedate']) && $item['duedate']): ?>
                &ndash; <span class="small"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($item['duedate'])?></span>
            <? endif; ?>            
        <? else: ?>
          <span class="text-danger text-nowrap">
            <i class="fa <?=$this->escapeHtmlAttr($icon)?> <?=$class?>"></i>
            <?=$this->escapeHtml($message)?>
          </span>
        <? endif; ?>
      </td>
    </tr>
  <? endforeach; ?>
<? if (count($this->statusItems) > 5): ?>
  <tr><td colspan="3"><a href="<?=$this->url('record', ['id' => $this->statusItems[0]['id']])?>"><?=count($this->statusItems) - 5?> <?=$this->transEsc('more')?> ...</a></td></tr>
<? endif; ?>
</table>
