<? /* Display thumbnail if appropriate: */ ?>
<?  $formats = $this->driver->getFormats();
    $icon = $this->mapper()->mapIcon($formats);
?>
<? if ($cover): ?>
  <? if (isset($this->link) && $this->link != '#'): ?>
    <a href="<?=$this->escapeHtmlAttr($this->link)?>" >
  <? elseif (isset($this->link) && $this->link == '#'): ?>
    <a href="#" class="modal-popup cover" data-toggle="modal" data-img-url="<?=$this->escapeHtmlAttr($cover); ?>">
  <? endif; ?>
  <img loading="lazy" <? if ($linkPreview): ?>data-linkpreview="true" <? endif; ?>class="img-responsive hidden-print <?=$icon?>" src="<?=$this->escapeHtmlAttr($cover); ?>"/>
  <? if ($this->link): ?>
    </a>
  <? endif; ?>
<? else: ?>
  <div class="recordcover unavailable hidden-print <?=$this->mapper()->mapIcon($this->driver->getFormats())?> medium">     
    <span class=""></span>
</div>
<? endif; ?>
