<?
  $this->headTitle($this->translate('ill_request_title'));
  $this->headScript()->appendFile("vendor/bootstrap-datepicker.js");   
  $this->headScript()->appendFile("vendor/bootstrap-datepicker.".$this->layout()->userLang.".min.js");    
  $this->headScript()->appendFile("ill.js");     

  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
    . '<li class="active">' . $this->transEsc('ill_request_title') . '</li>';
  $collapse = 'panel-collapse collapse';
  // avoid notices when using free form
  $params = !isset($params) ? [] : $params;
  $type = 'book';
  if (isset($this->driver)) {
    if ($this->driver->isJournal()) { $type = 'journal';}
    elseif ($this->driver->isContainerMonography()) { $type = 'article-book';}
    elseif ($this->driver->isArticle()){$type = 'article';}
  } else {
    $type = 'free';
  }  
  
?>
<div class="col-sm-12">    
    <h2><?=$this->illform($success, $this->driver)->getText('headline')?></h2>
    <noscript><p class="alert alert-danger"><?=$this->transEsc('Please enable JavaScript.')?></p></noscript>    
    <?=$this->flashmessages()?>
    <? if ($success && !empty($this->orderId) && $this->orderId > 0):?>
    <p><?=$this->transEsc('ill_request_submit_ok_text')?><strong><?=$this->escapeHtml($this->orderId)?></strong></p>
    <p><?=$this->transEsc('ill_request_submit_ok_text_2')?></p>
    <? endif; ?>
    <? if (!isset($success) || !$success): ?>
    <form class="<?=$type?> form-horizontal" id="form-ill" action="<?=$this->recordLink()->getUrl($this->driver)?>/ILLForm" method="POST" role="form">

        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">   
            <? $content = $this->illForm($success, $this->driver)->renderBibliographicFields() ?>
            <?= $this->partial('Helpers/ill/panel.phtml', [
                'title' => 'Bibliographic Details',
                'open'  => true,
                'content' => $content,
            ])?>
            <? $content = '<p><strong>'.$this->illForm($success, $this->driver)->getText('hint').'</strong></p>';
                $content .= $this->illform($success, $this->driver)->renderCopies();
            ?>
            <?= $this->partial('Helpers/ill/panel.phtml', [
                'title' => 'paperdata',
                'open'  => $this->illform($success, $this->driver)->isVisibleCopies(),
                'content' => $content,
            ])?>        
            <? $content = $this->render('Helpers/ill/delivery.phtml', ['params' => $params, 'driver' => $this->driver])?>        
            <?= $this->partial('Helpers/ill/panel.phtml', [
                'title' => 'delivery_conditions',
                'open'  => true,
                'content' => $content,

            ])?>        
            <? $content = $this->render('Helpers/ill/login.phtml', ['params' => $params, 'driver' => $this->driver])?> 
            <?= $this->partial('Helpers/ill/panel.phtml', [
                'title' => 'Benutzerdaten',
                'open'  => true,
                'content' => $content,
            ])?> 
            <br/>
            <div class="form-group form-group-sm">                 
                <div class="col-sm-1 col-xs-2">
                    <input type="checkbox" required="true" class="" id="agree-commercial-use" name="agree-commerial-use"/>
                </div>
                <label class="control-label col-xs-10 col-sm-11" for="agree-commercial-use">* <?=$this->transEsc('ill_commercial_use')?></label>
            </div>
            <div class="form-group form-group-sm"> 
                <div class="col-sm-12">
                    <input id="ill-submit" type="submit" class="btn btn-primary<?=$this->submitDisabled?' disabled': ''?>" value="<?=$test ? $this->transEsc('Test Order') : $this->transEsc('Order') ?>"/>            
                    <p>* <?=$this->transEsc('This field is required')?></p>
                                    
                </div>  
            </div>
        </div>
    </form> 
    <? endif; ?>
</div>
